syscall-y += syscall_table_64.h

generic-y += cache.h
generic-y += early_ioremap.h
generic-y += extable.h
generic-y += kvm_para.h
generic-y += mcs_spinlock.h
generic-y += param.h
generic-y += parport.h
generic-y += string.h
generic-y += tlb.h
generic-y += user.h
