# Retained only for explicit manual `make ... ARCH=orlix vmlinux` Linux
# Kbuild compatibility checks. Normal Orlix proof does not build or
# consume this linked-image path.
extra-y += vmlinux.lds

obj-y += cpuinfo.o
obj-y += idle.o
obj-y += irq.o
obj-y += hosted_exec.o
obj-y += ptrace.o
obj-y += reboot.o
obj-y += setup.o
obj-y += process.o
obj-y += signal.o
obj-y += syscall.o
obj-y += time.o
obj-y += traps.o
