# SPDX-License-Identifier: GPL-2.0

TEST_GEN_PROGS := boot_profile_contract clone_thread_probe init_exec_probe mprotect_stack_probe pthread_attr_probe tls_syscall_probe virtio_mmio_probe_contract
TEST_GEN_PROGS_EXTENDED := kselftest_init

include ../lib.mk
