#ifndef PROCESS_GROUP_SESSION_CONTRACT_H
#define PROCESS_GROUP_SESSION_CONTRACT_H

int process_group_session_contract_public_group_and_session_identity_matches_init_task(void);
int process_group_session_contract_public_getpgid_zero_matches_current_group(void);
int process_group_session_contract_public_setpgid_moves_child_into_own_group(void);
int process_group_session_contract_public_setpgid_rejects_execed_child(void);
int process_group_session_contract_public_setsid_creates_new_session_for_non_leader(void);
int process_group_session_contract_public_setpgid_rejects_session_leader(void);

#endif
