#ifndef WAIT_JOB_CONTROL_CONTRACT_H
#define WAIT_JOB_CONTROL_CONTRACT_H

int wait_job_control_contract_no_children_returns_echild(void);
int wait_job_control_contract_specific_non_child_returns_echild(void);
int wait_job_control_contract_wnohang_returns_zero_for_running_child(void);
int wait_job_control_contract_reaps_exited_child(void);
int wait_job_control_contract_second_wait_after_reap_returns_echild(void);
int wait_job_control_contract_null_status_still_reaps_exited_child(void);
int wait_job_control_contract_reports_stopped_child_with_wuntraced(void);
int wait_job_control_contract_stopped_child_without_wuntraced_wnohang_returns_zero(void);
int wait_job_control_contract_stopped_child_is_not_reaped(void);
int wait_job_control_contract_reports_continued_child_with_wcontinued(void);
int wait_job_control_contract_continued_status_is_linux_wifcontinued(void);
int wait_job_control_contract_continued_report_is_consumed(void);
int wait_job_control_contract_pid_zero_selects_same_process_group(void);
int wait_job_control_contract_negative_pid_selects_process_group(void);
int wait_job_control_contract_child_stop_generates_sigchld_for_parent(void);
int wait_job_control_contract_child_continue_generates_sigchld_for_parent(void);
int wait_job_control_contract_child_exit_generates_sigchld_for_parent(void);
int wait_job_control_contract_public_waitpid_reports_exited_child_status(void);
int wait_job_control_contract_wait4_reports_exited_child_status(void);
int wait_job_control_contract_public_waitpid_reports_stopped_child_with_wuntraced(void);
int wait_job_control_contract_public_waitpid_reports_continued_child_with_wcontinued(void);
int wait_job_control_contract_waitid_reports_exited_child_status(void);
int wait_job_control_contract_waitid_wnowait_preserves_waitable_child(void);
int wait_job_control_contract_pty_background_read_stop_is_waitpid_visible(void);
int wait_job_control_contract_pty_background_write_tostop_stop_is_waitpid_visible(void);
int wait_job_control_contract_pty_vsusp_stop_is_waitpid_visible(void);
int wait_job_control_contract_waitpid_signal_interrupt_records_restart(void);
int wait_job_control_contract_clone_thread_is_not_waitable(void);

#endif
