ORLIXOS_DISTRIBUTION_ID := orlix
ORLIXOS_DISTRIBUTION_NAME := OrlixOS
ORLIXOS_DISTRIBUTION_CHANNEL := bundled
ORLIXOS_ROOT_MODES := $(ORLIX_OS_ROOT_MODES)
ORLIXOS_RELEASE_ROOT_MODE := $(ORLIX_OS_RELEASE_ROOT_MODE)
ORLIXOS_DEVELOPMENT_ROOT_MODE := $(ORLIX_OS_DEVELOPMENT_ROOT_MODE)
ORLIXOS_BASE_ROOT_DEVICE := $(ORLIX_OS_BASE_ROOT_DEVICE)
ORLIXOS_STATE_ROOT_DEVICE := $(ORLIX_OS_STATE_ROOT_DEVICE)

ORLIXOS_RELEASE_PACKAGES := init bash coreutils grep jq curl zsh
ORLIXOS_DEVELOPMENT_PACKAGES := $(ORLIXOS_RELEASE_PACKAGES)

ORLIXOS_PACKAGE_PROOF_LADDER := bash jq curl zsh
ORLIXOS_DOWNLOADED_BINARY_REPOSITORIES := deferred
