ORLIXOS_DISTRIBUTION_ID := orlix
ORLIXOS_DISTRIBUTION_NAME := OrlixOS
ORLIXOS_DISTRIBUTION_CHANNEL := bundled

ORLIXOS_RELEASE_PACKAGES := init bash
ORLIXOS_DEVELOPMENT_PACKAGES := $(ORLIXOS_RELEASE_PACKAGES)

ORLIXOS_PACKAGE_PROOF_LADDER := bash jq curl zsh
ORLIXOS_DOWNLOADED_BINARY_REPOSITORIES := deferred
