ORLIXOS_DISTRIBUTION_ID := orlix
ORLIXOS_DISTRIBUTION_NAME := OrlixOS
ORLIXOS_DISTRIBUTION_CHANNEL := bundled
ORLIXOS_ROOT_MODES := initramfs-only direct overlay
ORLIXOS_RELEASE_ROOT_MODE := direct
ORLIXOS_DEVELOPMENT_ROOT_MODE := overlay
ORLIXOS_BASE_ROOT_DEVICE := /dev/vda
ORLIXOS_STATE_ROOT_DEVICE := /dev/vdb

ORLIXOS_RELEASE_PACKAGES := init bash coreutils grep jq curl zsh
ORLIXOS_DEVELOPMENT_PACKAGES := $(ORLIXOS_RELEASE_PACKAGES)

ORLIXOS_PACKAGE_PROOF_LADDER := bash jq curl zsh
ORLIXOS_DOWNLOADED_BINARY_REPOSITORIES := deferred
