#ifndef ORLIX_SYSTEM_LINUX_KERNEL_TESTS_PTRACE_CONTRACT_H
#define ORLIX_SYSTEM_LINUX_KERNEL_TESTS_PTRACE_CONTRACT_H

int ptrace_contract_attach_detach_child_same_user_namespace(void);
int ptrace_contract_newuser_child_cannot_attach_parent_namespace_task(void);
int ptrace_contract_newuser_child_can_attach_same_namespace_task(void);
int ptrace_contract_regset_round_trips_general_registers(void);
int ptrace_contract_syscall_trace_records_entry_and_exit(void);
int ptrace_contract_cont_injects_pending_signal(void);
int ptrace_contract_attach_stop_is_waitpid_visible(void);
int ptrace_contract_syscall_stop_is_waitpid_visible(void);
int ptrace_contract_peek_poke_data_uses_virtual_memory(void);
int ptrace_contract_traceclone_records_event_message(void);
int ptrace_contract_clone3_set_tid_traceclone_records_requested_pid(void);
int ptrace_contract_traceexec_records_event_message(void);
int ptrace_contract_traceexit_records_event_message(void);
int ptrace_contract_signal_delivery_stop_can_be_suppressed(void);
int ptrace_contract_signal_delivery_stop_can_inject_signal(void);
int ptrace_contract_event_stop_status_encodes_event(void);

#endif /* ORLIX_SYSTEM_LINUX_KERNEL_TESTS_PTRACE_CONTRACT_H */
