#ifndef PTY_SESSION_CONTRACT_H
#define PTY_SESSION_CONTRACT_H

int pty_session_contract_boot_init_task_has_linux_session_identity(void);
int pty_session_contract_dev_tty_fails_without_controlling_terminal(void);
int pty_session_contract_pty_pair_allocates_master_and_slave_descriptors(void);
int pty_session_contract_pty_descriptors_appear_in_proc_self_fd(void);
int pty_session_contract_pty_fstat_reports_character_device(void);
int pty_session_contract_pty_write_master_read_slave(void);
int pty_session_contract_pty_write_slave_read_master(void);
int pty_session_contract_pty_nonblocking_read_without_data_returns_again(void);
int pty_session_contract_close_on_exec_closes_only_flagged_pty_descriptor(void);
int pty_session_contract_controlling_tty_attach_makes_dev_tty_usable(void);
int pty_session_contract_tcgetsid_matches_controlling_session(void);
int pty_session_contract_isatty_reports_true_for_pty_descriptors(void);
int pty_session_contract_isatty_reports_enotty_for_non_tty_directory(void);
int pty_session_contract_isatty_reports_ebadf_for_invalid_descriptor(void);
int pty_session_contract_controlling_tty_survives_dup_of_slave_descriptor(void);
int pty_session_contract_controlling_tty_clears_or_fails_predictably_after_close_policy(void);
int pty_session_contract_pty_fdinfo_reflects_flags_and_paths(void);
int pty_session_contract_session_leader_exit_hangs_up_foreground_pgrp(void);
int pty_session_contract_session_leader_tiocnotty_hangs_up_foreground_pgrp(void);

#endif
