#ifndef SIGNAL_SYSCALL_CONTRACT_H
#define SIGNAL_SYSCALL_CONTRACT_H

#ifdef __cplusplus
extern "C" {
#endif

int signal_syscall_contract_rt_sigaction_uses_linux_uapi_layout(void);
int signal_syscall_contract_sigaltstack_and_frame_policy(void);
int signal_syscall_contract_frame_writes_virtual_record(void);
int signal_syscall_contract_frame_records_handler_handoff(void);
int signal_syscall_contract_frame_records_mask_restorer_and_context(void);
int signal_syscall_contract_rt_sigreturn_restores_mask_and_altstack(void);
int signal_syscall_contract_rt_sigreturn_restores_frame_context_record(void);
int signal_syscall_contract_frame_contains_linux_ucontext(void);
int signal_syscall_contract_ignored_dispositions_do_not_queue_or_terminate(void);
int signal_syscall_contract_realtime_queue_preserves_multiplicity_and_order(void);
int signal_syscall_contract_frame_applies_handler_mask_nodefer_and_resethand(void);
int signal_syscall_contract_restart_metadata_follows_sa_restart(void);

#ifdef __cplusplus
}
#endif

#endif
