#ifndef IXLAND_SYSTEM_LINUX_KERNEL_TESTS_CGROUP_CONTRACT_H
#define IXLAND_SYSTEM_LINUX_KERNEL_TESTS_CGROUP_CONTRACT_H

int cgroup_contract_current_task_starts_in_root(void);
int cgroup_contract_child_inherits_parent_cgroup(void);
int cgroup_contract_proc_self_cgroup_reports_root(void);
int cgroup_contract_cgroupfs_creates_group_and_moves_current_task(void);
int cgroup_contract_cgroupfs_moves_child_and_proc_pid_reports_membership(void);
int cgroup_contract_cgroup_namespace_rebases_proc_and_cgroupfs_visibility(void);
int cgroup_contract_pids_controller_tracks_current_and_max(void);
int cgroup_contract_pids_max_rejects_extra_migration(void);
int cgroup_contract_freezer_blocks_and_releases_migration(void);
int cgroup_contract_subtree_control_accepts_pids_and_freezer(void);
int cgroup_contract_cgroup_namespace_open_fd_survives_reset_until_closed(void);
int cgroup_contract_mount_cgroup2_exposes_cgroupfs_view(void);
int cgroup_contract_rmdir_empty_cgroup_removes_from_hierarchy(void);
int cgroup_contract_rmdir_busy_cgroup_fails(void);
int cgroup_contract_rmdir_parent_with_child_fails_notempty(void);
int cgroup_contract_newuser_caps_are_scoped_to_cgroup_namespace_owner(void);

#endif /* IXLAND_SYSTEM_LINUX_KERNEL_TESTS_CGROUP_CONTRACT_H */
