#ifndef EPOLL_CONTRACT_H
#define EPOLL_CONTRACT_H

int epoll_contract_create_returns_fd(void);
int epoll_contract_create1_cloexec_sets_fd_cloexec(void);
int epoll_contract_ctl_add_pipe_read_end(void);
int epoll_contract_ctl_add_socketpair_read_end(void);
int epoll_contract_ctl_add_duplicate_returns_exist(void);
int epoll_contract_ctl_mod_updates_events(void);
int epoll_contract_ctl_del_removes_events(void);
int epoll_contract_wait_pipe_readable_after_write(void);
int epoll_contract_wait_socketpair_readable_after_write(void);
int epoll_contract_wait_blocks_until_pipe_write(void);
int epoll_contract_wait_timeout_returns_zero(void);
int epoll_contract_wait_signal_interrupt_returns_intr(void);
int epoll_contract_restart_syscall_reenters_wait(void);
int epoll_contract_wait_reports_pipe_hup_after_writer_close(void);
int epoll_contract_wait_pty_readable_after_peer_write(void);
int epoll_contract_fd_appears_in_proc_self_fd(void);
int epoll_contract_fdinfo_reports_flags(void);
int epoll_contract_syscall_surface_wait_pipe_readable(void);
int epoll_contract_pwait_mask_blocks_signal_until_pipe_ready(void);
int epoll_contract_fdinfo_reports_watched_descriptor(void);

#endif
