#ifndef NATIVE_SYSCALL_CONTRACT_H
#define NATIVE_SYSCALL_CONTRACT_H

#ifdef __cplusplus
extern "C" {
#endif

int native_syscall_contract_dispatches_fd_pipe_and_procfs(void);
int native_syscall_contract_dispatches_vm_identity_time_and_dirs(void);
int native_syscall_contract_enforces_vma_fault_policy(void);
int native_syscall_contract_munmap_gap_and_map_fixed_replace_policy(void);
int native_syscall_contract_mremap_grows_and_moves_mapping(void);
int native_syscall_contract_madvise_dontneed_discards_private_page(void);
int native_syscall_contract_maps_shared_file_and_syncs(void);
int native_syscall_contract_mremap_extends_shared_mapping_writeback(void);
int native_syscall_contract_msync_preserves_clean_shared_pages(void);
int native_syscall_contract_unlinked_shared_mapping_syncs_through_open_fd(void);
int native_syscall_contract_shared_file_mappings_are_coherent(void);
int native_syscall_contract_shared_file_mappings_are_coherent_across_reopen(void);
int native_syscall_contract_shared_file_mappings_are_coherent_across_hardlink(void);
int native_syscall_contract_clone_without_vm_copies_private_vmas(void);
int native_syscall_contract_clone_without_vm_preserves_shared_file_mappings(void);
int native_syscall_contract_ftruncate_updates_shared_mapping_fault_policy(void);
int native_syscall_contract_proc_self_maps_reports_permission_runs(void);
int native_syscall_contract_dev_zero_mmap_is_virtual_zero_memory(void);
int native_syscall_contract_virtual_memory_faults_queue_sigsegv_codes(void);
int native_syscall_contract_proc_pid_maps_and_status_reflect_child_task(void);
int native_syscall_contract_proc_vm_accounting_reports_mapped_pages(void);
int native_syscall_contract_proc_self_smaps_reports_vma_accounting(void);
int native_syscall_contract_proc_self_smaps_dirty_clears_after_madvise(void);
int native_syscall_contract_proc_self_smaps_reclaims_dontneed_residency(void);
int native_syscall_contract_dispatches_process_startup_syscalls(void);
int native_syscall_contract_registers_native_artifact_descriptor(void);
int native_syscall_contract_execs_sbin_init_through_syscall_surface(void);
int native_syscall_contract_returns_raw_negative_errno(void);
int native_syscall_contract_registered_program_uses_syscall_surface(void);

#ifdef __cplusplus
}
#endif

#endif
