#ifndef NATIVE_SYSCALL_CONTRACT_H
#define NATIVE_SYSCALL_CONTRACT_H

#ifdef __cplusplus
extern "C" {
#endif

int native_syscall_contract_dispatches_fd_pipe_and_procfs(void);
int native_syscall_contract_dispatches_vm_identity_time_and_dirs(void);
int native_syscall_contract_enforces_vma_fault_policy(void);
int native_syscall_contract_munmap_gap_and_map_fixed_replace_policy(void);
int native_syscall_contract_mremap_grows_and_moves_mapping(void);
int native_syscall_contract_madvise_dontneed_discards_private_page(void);
int native_syscall_contract_maps_shared_file_and_syncs(void);
int native_syscall_contract_mremap_extends_shared_mapping_writeback(void);
int native_syscall_contract_msync_preserves_clean_shared_pages(void);
int native_syscall_contract_private_file_mapping_msync_does_not_write_back_cow(void);
int native_syscall_contract_unlinked_shared_mapping_syncs_through_open_fd(void);
int native_syscall_contract_shared_mapping_survives_fd_close_and_syncs(void);
int native_syscall_contract_unlinked_shared_mapping_survives_fd_close_and_syncs(void);
int native_syscall_contract_security_capability_xattr_round_trips(void);
int native_syscall_contract_user_xattr_list_remove_round_trips(void);
int native_syscall_contract_flistxattr_reports_fd_user_attribute(void);
int native_syscall_contract_lxattr_targets_symlink_inode(void);
int native_syscall_contract_xattr_lifetime_tracks_rename_exchange_and_symlink_unlink(void);
int native_syscall_contract_shared_mapping_fault_policy_tracks_truncate_after_fd_close(void);
int native_syscall_contract_shared_file_mappings_are_coherent(void);
int native_syscall_contract_shared_file_mappings_are_coherent_across_reopen(void);
int native_syscall_contract_shared_file_mappings_are_coherent_across_hardlink(void);
int native_syscall_contract_shared_hardlink_mapping_fault_policy_tracks_truncate_after_original_unlink(void);
int native_syscall_contract_clone_without_vm_copies_private_vmas(void);
int native_syscall_contract_clone_without_vm_cows_private_file_mapping(void);
int native_syscall_contract_private_file_cow_smaps_reports_anonymous_dirty_page(void);
int native_syscall_contract_smaps_splits_mprotect_runs_and_preserves_dirty_counts(void);
int native_syscall_contract_map_fixed_gap_coalesces_compatible_anonymous_vmas(void);
int native_syscall_contract_private_file_cow_smaps_survives_munmap_gap(void);
int native_syscall_contract_private_file_cow_survives_truncate_and_clean_page_faults(void);
int native_syscall_contract_partial_truncate_zero_fills_and_mincore_tracks_pages(void);
int native_syscall_contract_partial_page_msync_and_shared_growth_writeback(void);
int native_syscall_contract_rename_updates_open_fd_and_mapping_identity(void);
int native_syscall_contract_mremap_fixed_preserves_private_file_cow_smaps(void);
int native_syscall_contract_mremap_fixed_coalesces_file_backed_neighbors(void);
int native_syscall_contract_mremap_fixed_rejects_zero_target(void);
int native_syscall_contract_mremap_fixed_rejects_overlapping_target(void);
int native_syscall_contract_mremap_fixed_grow_preserves_shared_file_mapping(void);
int native_syscall_contract_moved_shared_mapping_truncate_updates_fault_mincore_and_smaps(void);
int native_syscall_contract_madvise_split_vma_clears_each_permission_run(void);
int native_syscall_contract_private_file_madvise_dontneed_restores_file_page_after_cow(void);
int native_syscall_contract_mprotect_file_smaps_vmflags_follow_permission_runs(void);
int native_syscall_contract_vma_split_chain_preserves_permission_runs(void);
int native_syscall_contract_clone_without_vm_preserves_shared_file_mappings(void);
int native_syscall_contract_ftruncate_updates_shared_mapping_fault_policy(void);
int native_syscall_contract_proc_self_maps_reports_permission_runs(void);
int native_syscall_contract_dev_zero_mmap_is_virtual_zero_memory(void);
int native_syscall_contract_virtual_memory_faults_queue_sigsegv_codes(void);
int native_syscall_contract_prot_none_read_fault_queues_sigsegv_accerr(void);
int native_syscall_contract_stack_guard_write_grows_and_below_guard_faults(void);
int native_syscall_contract_partial_copy_records_sigbus_fault_address(void);
int native_syscall_contract_partial_copy_records_fault_address(void);
int native_syscall_contract_proc_pid_maps_and_status_reflect_child_task(void);
int native_syscall_contract_proc_vm_accounting_reports_mapped_pages(void);
int native_syscall_contract_proc_status_reports_vm_high_water_fields(void);
int native_syscall_contract_proc_self_smaps_reports_vma_accounting(void);
int native_syscall_contract_proc_self_smaps_dirty_clears_after_madvise(void);
int native_syscall_contract_proc_self_smaps_reclaims_dontneed_residency(void);
int native_syscall_contract_mincore_reports_virtual_residency(void);
int native_syscall_contract_read_fault_restores_mincore_residency(void);
int native_syscall_contract_mincore_uses_file_offset_for_truncate_residency(void);
int native_syscall_contract_truncated_file_mapping_fault_queues_sigbus(void);
int native_syscall_contract_truncated_file_mapping_write_fault_queues_sigbus(void);
int native_syscall_contract_dispatches_process_startup_syscalls(void);
int native_syscall_contract_dispatches_shell_fd_vfs_syscalls(void);
int native_syscall_contract_dispatches_statx_syscall(void);
int native_syscall_contract_dispatches_exit_and_waitid_syscalls(void);
int native_syscall_contract_registers_native_artifact_descriptor(void);
int native_syscall_contract_execs_sbin_init_through_syscall_surface(void);
int native_syscall_contract_returns_raw_negative_errno(void);
int native_syscall_contract_registered_program_uses_syscall_surface(void);
int native_syscall_contract_mlibc_linux_sysdeps_inventory_is_kernel_owned(void);

#ifdef __cplusplus
}
#endif

#endif
