#ifndef PIPE_CONTRACT_H
#define PIPE_CONTRACT_H

int pipe_contract_rejects_null_pipefd(void);
int pipe_contract_allocates_lowest_available_descriptors(void);
int pipe_contract_read_end_is_readable_only(void);
int pipe_contract_write_end_is_writable_only(void);
int pipe_contract_round_trip_read_write(void);
int pipe_contract_read_consumes_bytes_in_order(void);
int pipe_contract_read_empty_no_writers_returns_eof(void);
int pipe_contract_read_empty_nonblocking_returns_again(void);
int pipe_contract_write_no_readers_returns_pipe(void);
int pipe_contract_pipe2_cloexec_sets_both_descriptors(void);
int pipe_contract_pipe2_nonblock_sets_both_descriptors(void);
int pipe_contract_pipe2_rejects_unsupported_flags(void);
int pipe_contract_dup_shares_pipe_object(void);
int pipe_contract_close_on_exec_closes_only_flagged_pipe_descriptor(void);
int pipe_contract_fstat_reports_fifo(void);
int pipe_contract_lseek_returns_spipe(void);
int pipe_contract_pread_returns_spipe(void);
int pipe_contract_pwrite_returns_spipe(void);
int pipe_contract_getdents_returns_notdir(void);
int pipe_contract_poll_read_end_readable_when_data_available(void);
int pipe_contract_poll_read_end_hup_when_no_writers(void);
int pipe_contract_poll_write_end_writable_when_capacity_available(void);
int pipe_contract_poll_invalid_fd_returns_nval(void);
int pipe_contract_proc_self_fd_shows_pipe_descriptor(void);
int pipe_contract_proc_self_fdinfo_shows_pipe_flags(void);
int pipe_contract_blocking_read_wakes_when_writer_writes(void);
int pipe_contract_blocking_read_interrupted_by_signal(void);
int pipe_contract_blocking_write_wakes_when_reader_drains(void);
int pipe_contract_write_no_readers_queues_sigpipe(void);

#endif
