#ifndef IXLANDSYSTEMLINUXKERNELTESTS_PROCFSNAMESPACECONTRACT_H
#define IXLANDSYSTEMLINUXKERNELTESTS_PROCFSNAMESPACECONTRACT_H

#ifdef __cplusplus
extern "C" {
#endif

int procfs_namespace_contract_ns_directory_opens(void);
int procfs_namespace_contract_ns_links_are_linux_shaped(void);
int procfs_namespace_contract_unshare_newuts_changes_uts_link(void);
int procfs_namespace_contract_unshare_newns_changes_mnt_link(void);
int procfs_namespace_contract_proc_pid_status_aliases_current_task(void);
int procfs_namespace_contract_pid_namespace_status_reports_nspid(void);
int procfs_namespace_contract_proc_pid_status_reports_target_credentials(void);
int procfs_namespace_contract_proc_status_reports_groups_and_capabilities(void);
int procfs_namespace_contract_proc_pid_stat_cwd_and_exe_report_target_task(void);
int procfs_namespace_contract_proc_pid_fd_and_fdinfo_paths_are_target_aware(void);
int procfs_namespace_contract_proc_pid_fd_dir_lists_target_inherited_fds_after_parent_close(void);
int procfs_namespace_contract_fdinfo_flags_are_per_task_descriptor_state(void);
int procfs_namespace_contract_child_close_does_not_close_parent_descriptor(void);
int procfs_namespace_contract_fdinfo_offset_tracks_shared_open_file_description(void);
int procfs_namespace_contract_proc_pid_cmdline_environ_and_comm_report_target_task(void);
int procfs_namespace_contract_proc_pid_stat_status_and_maps_report_target_task(void);
int procfs_namespace_contract_proc_pid_status_stat_and_fdinfo_have_linux_fields(void);
int procfs_namespace_contract_proc_pid_stat_reports_tty_start_rss_and_exit_signal(void);
int procfs_namespace_contract_proc_pid_mountinfo_uses_target_mount_namespace(void);
int procfs_namespace_contract_root_files_are_readable(void);

#ifdef __cplusplus
}
#endif

#endif /* IXLANDSYSTEMLINUXKERNELTESTS_PROCFSNAMESPACECONTRACT_H */
